### ISSUE TITLE
Commonjs incompatibility?

### ISSUE THREAD

**Issue by theoparis** [ETSOO/restclient#1]
I got the following error when running tests that utilize this library with ts-node:

```
test/containers.test.ts 2> /home/theo/dev/docker-api/node_modules/.pnpm/@etsoo+restclient@1.0.35/node_modules/@etsoo/restclient/lib/index.js:1
test/containers.test.ts 2> import { AxiosApi } from './AxiosApi';
test/containers.test.ts 2> ^^^^^^
test/containers.test.ts 2> 
test/containers.test.ts 2> SyntaxError: Cannot use import statement outside a module
```

I am using a typescript setup with commonjs, and I imported this library like so:
```
import { ApiAuthorizationScheme, createClient, IApi } from "@etsoo/restclient";

```

I need commonjs support because all of the test runners I've tried won't work with typescript and ESM :(

**Comment by creepinson** [comment]
So  I managed to make a fork of this library that adds ESM support with an additional tsconfig.esm.json and a "module": "./lib/esm.index.js" option in package.json. However, @etsoo/shared is also not compatible so I won't be able to get this one to work.

**Comment by garryxiao** [comment]
@creepinson It's a new topic for me. I will try to add support for commonjs in the comming month and will let you know when it's ready.

**Comment by garryxiao** [comment]
@creepinson I have implemented the CommonJs support and have tested with the latest version of NodeJs with express now it should work. Please double check for me and if it's ready, I will close the issue. Thanks.
